Adds welcome page
kdoran/lookout pull request #25
Opened 2018-12-16 18:10 UTC by Olamuhammed

This just adds a welcome page route

2018-12-17 06:26 UTC, kdoran requested changes
Nice work m-man 🎉 first PR :)

few things to try out:

1. your welcome file only needs one import :)
2. try running the command `standard` and see what errors it says, it's an npm script 
3. there's a convention for file names that are "containers" (which we use as controllers of sorts) which is `FileNameContainer`, also all the imports for containers in the same place in the app file

2018-12-21 16:50 UTC, kdoran commented on app/app.js
> +import Welcome from './containers/WelcomeContainer'
you'd still want this to be called `WelcomeContainer` to match the others (doesn't really matter but for the sake of convention).

2018-12-21 16:50 UTC, kdoran commented on app/app.js
> +          <Route path='/Welcome' component={Welcome} />
the route would be lowercase `welcome`

2018-12-21 16:50 UTC, kdoran commented on app/components/Welcome.js
> +class Welcome extends Component{
same here keep the naming uniform `WelcomeContainer`

2018-12-21 16:50 UTC, kdoran commented on app/containers/SetupCouchContainer.js
> +    this.setState({ inputUrl })
lol you don't like my newfound lack of spaces in object destructuring ;)

2018-12-21 16:50 UTC, kdoran commented on app/containers/SetupCouchContainer.js
> +        <a href='https://github.com/kdoran/lookout'>Lookout on GitHub</a><br />
what's this little `<br />` guy about

2018-12-21 16:50 UTC, kdoran commented on app/containers/WelcomeContainer.js
> +import React, { Component } from 'react'
there are two of these files now :)

2018-12-30 00:14 UTC, Olamuhammed commented
Hey, made the changes to name and deleted somethings too

2023-09-21 17:12 UTC, closed without merging